<h1><strong>NumPY</strong></h1>

***
**NumPy Nedir ?**
- Numerical Python
- Bilimsel Hesaplamalar icin kullanilir.
- Listelere numpy arrayleri benzer fakat sabit veri tipi vardır ve butun listeyi tutmaya gerek duymaz.
- Vektorel operasyonlardır.

**Neden Numpy**

In [41]:
#Liste kullanilarak

List1 = [1,2,3,4]
List2 = [5,6,7,8]
List3 = [ ]         #List3 = List1 * List2
for i in range(0,len(List1)):
    List3.append(List1[i]*List2[i])

List3

[5, 12, 21, 32]

In [47]:
import numpy as np      # Numpy import edildi.
List1 = np.array([1,2,3,4])      # Numpy array'i tanimlandi.
List2 = np.array([5,6,7,8])      # Numpy array'i tanimlandi.
List3 = List1 * List2         # Vektorel olarak carpildi.
List3

array([ 5, 12, 21, 32])

**Numpy Array'i Olusturmak**

In [100]:
import numpy as np

Arr1D = np.array([1,2,3,4])     # 1 boyutlu
print(Arr1D)

Arr2D = np.array([[1,2,3,4],[5,6,7,8]])    # 2 boyutlu
print(Arr2D)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


- Sabit tip 

In [72]:
import numpy as np
ConstType = np.array([3.33,4,2,1.1])      # Array icindeki tip float oldu.
ConstType

array([3.33, 4.  , 2.  , 1.1 ])

**Sifirdan Array Olusturmak**

In [81]:
import numpy as np
np.zeros(10,dtype = int)      # np.sifirlardanolusan(elamans,dtype bilgisi)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [66]:
import numpy as np
np.ones((3,3),dtype = int)      # np.bir((boyut bilgisi),dtype bilgisi)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [68]:
import numpy as np
np.full((2,4),11)      # np.full(boyut bilgisi,hangi sayidan)

array([[11, 11, 11, 11],
       [11, 11, 11, 11]])

In [102]:
import numpy as np

Aralik = np.arange(0,10,2)      # 0-10 arasi 2'ser
print(Aralik)

ZeroToOne = np.linspace(0,1,10)
print(ZeroToOne)                # 0-1 arasinda rastgele 10 sayi

LogArr = np.logspace(1,3,10)    # 10-1000 arasi sayilar
print(LogArr)

RandomArray = np.random.normal(10,2,(3,3))
print(RandomArray)          # np.random.normal(ortalamasi 10,standart sap 2,boyut bilgisi)

IntArray = np.random.randint(0,10,(3,3))  # 0-10 arasi 3x3 integer array
print(IntArray)

[0 2 4 6 8]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[  10.           16.68100537   27.82559402   46.41588834   77.42636827
  129.1549665   215.443469    359.38136638  599.48425032 1000.        ]
[[ 8.91338629 11.43857923 10.15566059]
 [ 8.01325195 11.50542901  8.02117089]
 [12.29425007  9.71329405 11.53130932]]
[[3 3 5]
 [6 6 6]
 [9 0 5]]


**Dizi Islemleri**

**Indeksleme**

In [170]:
import numpy as np

IndeksArr = np.random.randint(1,10,5)
print(IndeksArr)
print(IndeksArr[2])
print(IndeksArr[-1])

x = np.array([[1,2,3,4],[5,6,7,8,]])
print(x[1,1])

[3 4 2 7 3]
2
3
6


**Kosullu Eleman Islemleri**

In [179]:
import numpy as np

v = np.array([[1,2,3,4],[5,6,7,8,]])
print(v[v>3])

[4 5 6 7 8]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 3  6  9 12]
 [15 18 21 24]]


**Matematiksel Islemler**

In [200]:
import numpy as np

v = np.array([[-1,2,3,4],[5,-6,7,8,]])

print( np.add(v,1) )
print( np.subtract(v,1) )
print( np.mod(v,2) )
print( np.absolute(v))

print(np.sin(v))

w = np.array([[1,2,3,4],[5,6,7,8,]])
print(np.log10(w))

[[ 0  3  4  5]
 [ 6 -5  8  9]]
[[-2  1  2  3]
 [ 4 -7  6  7]]
[[1 0 1 0]
 [1 0 1 0]]
[[1 2 3 4]
 [5 6 7 8]]
[[-0.84147098  0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427  0.2794155   0.6569866   0.98935825]]
[[0.         0.30103    0.47712125 0.60205999]
 [0.69897    0.77815125 0.84509804 0.90308999]]


**Dizi Manipulasyonu**
- ndim: boyut sayisi
- shape: boyut bilgisi
- size: toplam eleman sayisi
- dtype: array veri tipi

In [90]:
import numpy as np

IntArray = np.random.randint(1,9,(2,4))
print(IntArray.ndim)
print(IntArray.shape)
print(IntArray.size)
print(IntArray.dtype)

2
(2, 4)
8
int32


**Reshape**

In [107]:
import numpy as np

Reshaping = np.arange(1,10,2)
print(Reshaping)

Reshaping = Reshaping.reshape(5,1)      # yeniden boyutlandirma
print(Reshaping)

[1 3 5 7 9]
[[1]
 [3]
 [5]
 [7]
 [9]]


**Concatenation**

In [124]:
import numpy as np

x = np.array([[1,2,3,4],[5,6,7,8,]])
y = np.array([[1,2,3,4],[5,6,7,8,]])
z = np.concatenate([x,y])
print(z)

RowArr = np.concatenate([x,y],axis = 0)       # Satir olarak birlestirme
print(RowArr)

ColArr = np.concatenate([x,y],axis = 1)       # Sutun olarak birlestirme
print(ColArr)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]


**Splitting**

In [148]:
import numpy as np

x = np.array([1,2,3,4,5,6,7,8])
Row1,Row2,Row3 = np.split(x,[3,5])           # 3'den ayir , 5' den ayir
print(Row1)
print(Row2)
print(Row3)

z = np.array([[1,2,3,4],[5,6,7,8,]])         # satir olarak bol.
Top,Bottom = np.vsplit(y,[1])
print(Top)

z = np.array([[1,2,3,4],[5,6,7,8,]])         # sutun olarak bol
Left,Right = np.hsplit(z,[2])
print(Left)
print(Right)

[1 2 3]
[4 5]
[6 7 8]
[[1 2 3 4]]
[[1 2]
 [5 6]]
[[3 4]
 [7 8]]


**Sorting**

In [152]:
import numpy as np

UnOrdered = np.array([3,6,1,8,4,2])
Ordered = np.sort(UnOrdered)
print(Ordered)

[1 2 3 4 6 8]


**Transpose**

In [155]:
import numpy as np

z = np.array([[1,2,3,4],[5,6,7,8,]]) 
z = z.T
print(z)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


**Istatiksel ve Matematiksel Fonksiyonlar**

In [203]:
import numpy as np

v = np.array([[-1,2,3,4],[5,-6,7,8,]])

print( np.add(v,1) )                      # toplama
print( np.subtract(v,1) )                     # cikarma
print( np.mod(v,2) )                     # mod
print( np.absolute(v))                     # mutlak

print(np.sin(v))                     # sinus

w = np.array([[1,2,3,4],[5,6,7,8,]])                     
print(np.log10(w))                     # logaritma


print(np.median(w))                     # medyan
print(np.mean(w))                     # aritmetik ort.
print(np.std(w))                     # standart sapma
print(np.nanmedian(w))                     # nan degerleri almadan medyan hesaplama

[[ 0  3  4  5]
 [ 6 -5  8  9]]
[[-2  1  2  3]
 [ 4 -7  6  7]]
[[1 0 1 0]
 [1 0 1 0]]
[[1 2 3 4]
 [5 6 7 8]]
[[-0.84147098  0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427  0.2794155   0.6569866   0.98935825]]
[[0.         0.30103    0.47712125 0.60205999]
 [0.69897    0.77815125 0.84509804 0.90308999]]
4.5


**Boolean Diziler ve Filtreleme**

In [214]:
import numpy as np

Arr = np.array([1, 0, -1, 3])
BoolArr = Arr.astype(bool)

print(BoolArr)

Arr2 = np.array([1, 2, 0, -1])

print(Arr2 > 0)

print(Arr2 >= 2)

[ True False  True  True]
[ True  True False False]
[False  True False False]


In [216]:
Data = np.random.randn(5, 4)
print(Data)

BoolFilter = (Data[:, 2] > 0)
FilteredData = Data[BoolFilter]
print(FilteredData)

[[ 0.80487926 -1.3347932  -0.75873165 -0.98320211]
 [ 0.04994912  1.05661514  0.79458138 -0.12355563]
 [ 0.13078191  1.2191129   0.0935127   1.72415448]
 [ 0.37193774  0.16151057 -2.16182468 -0.61757426]
 [ 0.32119824  1.8638254  -0.58166956  0.5932326 ]]
[[ 0.04994912  1.05661514  0.79458138 -0.12355563]
 [ 0.13078191  1.2191129   0.0935127   1.72415448]]


**Matrisler ve Lineer Cebir**

In [221]:
import numpy as np

a = np.array([[1.0, 2.0], [3.0, 4.0]])
print('a:', a)
print('transpoze a:', a.transpose())
print('tersi a:', np.linalg.inv(a))

c = np.array([[0.0, -1.0], [1.0, 0.0]])
print(c @ c) #matrix çarpımı


a: [[1. 2.]
 [3. 4.]]
transpoze a: [[1. 3.]
 [2. 4.]]
tersi a: [[-2.   1. ]
 [ 1.5 -0.5]]
[[-1.  0.]
 [ 0. -1.]]
